/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        byte iguana;
        iguana=4;
        System.out.println(iguana);
        System.out.println(new App().getGreeting());
    }
}
